### ISSUE TITLE
Σαλείμ (4530)

### ISSUE THREAD

**Issue by jcuenod** [biblicalhumanities/Dodson-Greek-Lexicon#2]
Any idea why Dodson wouldn't have an entry for Σαλείμ (occurs John 3:23)?

There are fewer than 10 strongs numbers that nestle1904 uses that Dodson doesn't have an entry for and the others are relatively easy to make sense of. In this case, I'm guessing it's because he thought it should be either Salem or Salamis (but I've only looked into this enough to know that it doesn't look as though we know with certainty where John is referring to). I'm just wondering what Dodson's response to Strong's `4530` is.

**Comment by jonathanrobie** [comment]
I don't know.  We used Dodson's lexicon basically as-is, we have not been
updating or modifying it.

**Comment by jcuenod** [comment]
Okay, thanks

**Comment by jcuenod** [comment]
In Mounce's dictionary, under "Σαλαμίς" he says:

> Saleim, also formed as Σαλίμ (G4890 [sic]). John was baptizing at Aenon near Saleim, Jn. 3:26* [sic].

Although now I realise that this is probably just a mistake and should be under 4530 (instead of 4529)...
